# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IVR Plugin (Residential Vulnerability Index)
                                 A QGIS plugin
 Calculates the Residential Vulnerability Index (IVR) using cadastral and spatial data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-04-07
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Manuel Blasco Jiménez
        email                : manuel2blasco@edu.uah.es
        description          : QGIS plugin for the analysis of residential vulnerability based on cadastral data
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software: you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation, either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This software has been developed as part of formal academic research. *
 *   If you use this plugin, please cite the corresponding work.           *
 *                                                                         *
 ***************************************************************************/
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IVR class from file IVR.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ivr_plugin import IVR
    return IVR(iface)
