# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IVR Plugin (Residential Vulnerability Index)
                                 A QGIS plugin
 Calculates the Residential Vulnerability Index (IVR) using cadastral and spatial data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-04-07
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Manuel Blasco Jiménez
        email                : manuel2blasco@edu.uah.es
        description          : QGIS plugin for the analysis of residential vulnerability based on cadastral data
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software: you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation, either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This software has been developed as part of formal academic research. *
 *   If you use this plugin, please cite the corresponding work.           *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

from .resources import *
from .ivr_plugin_dialog import IVRDialog
import os.path

class IVR:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(self.plugin_dir, 'i18n', 'IVR_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&IVR')
        self.first_start = None

    def tr(self, message):
        return QCoreApplication.translate('IVR', message)

    def add_action(
        self, icon_path, text, callback, enabled_flag=True,
        add_to_menu=True, add_to_toolbar=True, status_tip=None,
        whats_this=None, parent=None):

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)
        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.iface.addToolBarIcon(action)
        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        icon_path = ':/plugins/ivr_plugin/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'IVR'),
            callback=self.run,
            parent=self.iface.mainWindow()
        )
        self.first_start = True

    def unload(self):
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&IVR'), action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        from qgis.PyQt.QtWidgets import QMessageBox
        import traceback
    
        try:
            self.dlg = IVRDialog()
        except Exception:
            tb = traceback.format_exc()
            QMessageBox.critical(self.iface.mainWindow(), "IVR - Error creando el diálogo", tb)
            print(tb)
            return
    
        self.dlg.show()
