# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IVR Plugin (Residential Vulnerability Index)
                                 A QGIS plugin
 Calculates the Residential Vulnerability Index (IVR) using cadastral and spatial data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-04-07
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Manuel Blasco Jiménez
        email                : manuel2blasco@edu.uah.es
        description          : QGIS plugin for the analysis of residential vulnerability based on cadastral data
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software: you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation, either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This software has been developed as part of formal academic research. *
 *   If you use this plugin, please cite the corresponding work.           *
 *                                                                         *
 ***************************************************************************/
"""

###############################################################################
# B1 IMPORTS (evitar imports pesados en tiempo de carga del plugin)
###############################################################################

import os

from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtWidgets import QFileDialog, QMessageBox

from qgis.core import (QgsVectorLayer, QgsApplication, Qgis, 
                       QgsTask, QgsProject, QgsMessageLog)
from qgis.utils import iface

# Modulos propios 
from .funciones_auxiliares import modulos_ivr as ivr
from .funciones_auxiliares import ui_texts as uit
from .funciones_auxiliares import ui_bindings as uib
from .funciones_auxiliares import ivr_fig as aux
from .funciones_auxiliares import ivr_cat as cat
from .funciones_auxiliares import ivr_qgs as qgs

# Interfaz 
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'ivr_plugin_dialog_base.ui'
))

class IVRDialog(QtWidgets.QDialog, FORM_CLASS):
    
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)

        uit.setup_ui_texts(self)
        uit.setup_combo_metodos(self)
        uib.setup_ui_logic(self)
        uib.setup_connections(self)
        uib.setup_defaults(self)

    titulos = {
        "entrada": "Seleccionar carpeta de entrada",
        "salida": "Seleccionar carpeta de salida",
    }
        
    def seleccionar_carpeta(self, tipo):
        "Función para la selección y visulización de rutas"
        
        titulo = f"Seleccionar carpeta de {tipo}"
        ruta = QFileDialog.getExistingDirectory(self, titulo, "",
               QFileDialog.ShowDirsOnly)
    
        if not ruta:
            return
    
        if tipo == "entrada":
            self.ruta_entrada = ruta
            if hasattr(self, "visualizar_entrada"):
                self.visualizar_entrada.setText(ruta)
    
        elif tipo == "salida":
            self.ruta_salida = ruta
            if hasattr(self, "visualizar_salida"):
                self.visualizar_salida.setText(ruta)
                
    def verificacion_front(self):
    
        # V1: Ruta de entrada obligatoria
        ruta_entrada = getattr(self, "ruta_entrada", None)
        if not ruta_entrada:
            QMessageBox.warning(
                self,
                "Falta información",
                "No existe ruta de entrada, seleccione una para iniciar el proceso."
            )
            return False
    
        # V2: Si hay método, debe elegirse GAU o LOC
        hay_metodo = hasattr(self, "bt_met") and self.bt_met.currentIndex() != 0
    
        gau = hasattr(self, "bt_ivr_gau") and self.bt_ivr_gau.isChecked()
        loc = hasattr(self, "bt_ivr_loc") and self.bt_ivr_loc.isChecked()
    
        if hay_metodo and not (gau or loc):
            QMessageBox.warning(
                self,
                "Falta información",
                "Ha seleccionado un método de clasificación, pero no el tipo de IVR (GAU o LOC)."
            )
            return False
    
        return True
      
    def ejecutar_proceso(self):
        # 1) Validar inicio
        if not self.verificacion_front():
            return
    
        # 2) Establecer rutas entrada y salida 
        input_path = getattr(self, "ruta_entrada", None)
        output_path = getattr(self, "ruta_salida", None)
        
        # 3) Crear instancia para envío de la tarea al Task Manager
        self.task = TareaProcesamientoIVR(
            
            # Rutas procesos (2)
            input_path = input_path,                     # String 
            output_path = output_path,                   # String 
            # Información capa (4)
            val_org = self.bt_org.isChecked(),
            val_nor = self.bt_nor.isChecked(),
            val_gau = self.bt_gau.isChecked(),
            val_adc = self.br_adc.isChecked(),
            # Información Clasificador GAU (4)
            metodo = self.bt_met.currentText(),         # String 
            clases = self.bt_rag.value(),               # Int 
            ivr_gau = self.bt_ivr_gau.isChecked(),
            ivr_loc = self.bt_ivr_loc.isChecked(),
            # Parámetros Auxiliares (2) 
            val_t15 = self.bt_15.isChecked(),
            val_mix = int(self.bt_mix.opacity() * 100), # Float 
            val_crs = self.bt_crs.currentText(),        # String!
            # Información Auxiliar (4)
            fsig = self.bt_fsig.isChecked(),
            fnor = self.bt_fnor.isChecked(),
            csvmun = self.bt_mun.isChecked(),
            csvpro = self.bt_pro.isChecked(),
            
        )
    
        QgsApplication.taskManager().addTask(self.task)

###############################################################################
# B3 Task en segundo plano
###############################################################################

class TareaProcesamientoIVR(QgsTask):

    def __init__(self, 
                input_path, output_path,
                val_org, val_nor, val_gau, val_adc, 
                metodo, clases, ivr_gau, ivr_loc, val_t15, val_mix, val_crs, 
                fsig, fnor, csvmun, csvpro):
        super().__init__("Procesamiento IVR", QgsTask.CanCancel)
        
        # Heradas .ui
        self.input_path = input_path  
        self.output_path = output_path                  
        self.val_org = val_org
        self.val_nor = val_nor
        self.val_gau = val_gau
        self.val_adc = val_adc
        self.metodo = metodo       
        self.clases = clases
        self.ivr_gau = ivr_gau
        self.ivr_loc = ivr_loc
        self.val_t15 = val_t15 
        self.val_mix = val_mix 
        self.val_crs = val_crs        # String!
        self.fsig = fsig
        self.fnor = fnor
        self.csvmun = csvmun
        self.csvpro = csvpro
        # Otros
        self.exception = None
        self.gpkg_path = None
        self.layer_name = "IVR"
        self._result_ok = False
        
        # Mensaje iface no funcione en hilo paralelo (Sólo LOGS!!)

        iface.messageBar().pushMessage(
            "Descomprimiendo",
            "Puede tardar unos minutos. Provincias con ZIP partido (requieren 7-Zip): "
            "Alicante, A Coruña, Barcelona, Madrid, Málaga, Murcia, Sevilla, Tarragona, Toledo, Valencia. "
            "Descarga: https://www.7-zip.org/",
            level=Qgis.Info, 
            duration = 15
        )

    def run(self):
        
        try:
            ruta_base = self.input_path
            carpeta_des = os.path.join(ruta_base, "Descomprimidos")
            
            if not os.path.isdir(carpeta_des):
                descomprimidos = cat.descomprimir_peticiones(ruta_base, carpeta_des)
                ruta_lectura = ruta_base
                
                if descomprimidos: 
                    resumen, ruta_7zip = cat.descomprimir_recursivo(
                        carpeta_des, borrar_originales=True)
                    ruta_lectura = carpeta_des
                    
                    # Información si se descomprime
                    exi = resumen["exitos"]
                    err = resumen["errores"]
                    res = resumen["warnings"]
                    # En registro de Qgis
                    QgsMessageLog.logMessage(
                        "Descomprimiendo archivos...\n"
                        f"Instalado 7-zip: {ruta_7zip}\n"
                        f".ZIP OK: {exi}\n"
                        f".ZIP Fail: {err}\n"
                        f".ZIP Warnings: {res}\n", "IVR", Qgis.Info)
                else: 
                    QgsMessageLog.logMessage(
                        "Sin descomprimir archivos...\n", "IVR", Qgis.Info)
                    ruta_lectura = ruta_base
        except:
            iface.messageBar().pushMessage(
                "Error en la entrada de datos...",
                level = Qgis.Critical, duration = 12)

        try:
            
            self.setProgress(1)
            # Observa que modalidaad del IVR se grafica
            if self.ivr_gau:
                col_ivr = "ivr_gau"
            else:
                col_ivr = "ivr_loc"
                
            if self.output_path:
                output_path = self.output_path
            else:
                output_path = os.path.join(self.input_path, "resultados")
                
            
            ivr.log_estado_ui(self, col_ivr)
            
            # Aplicado Simbología 
            if self.metodo != "Sin clasificar":
                # Aplicar función con simbologia 
                df_mun, dfs_bi, dfs_ivr, df_pro, dic_gau, col_class = ivr.logica_principal_ivr(
                    ruta_base = ruta_lectura,
                    metodo = self.metodo,
                    rangos = self.clases,
                    col_ivr = col_ivr,
                    val_t15 = self.val_t15,
                    crs_ui = self.val_crs,
                    umbral_mix = self.val_mix,
                    task = self
                )
                
                dfs_ivr = ivr.informacion_capa_ivr(dfs_ivr, colcl = col_class,
                          inf_add = self.val_adc, inf_org = self.val_org, 
                          inf_nor = self.val_nor, inf_cls = self.val_gau)
                    
                # Guardar datos renderizado 
                self.dic_gau = dic_gau
                self.col_ivr = col_ivr
            else: 
                # Aplicar función sin simbologia 
                df_mun, dfs_bi, dfs_ivr, df_pro = ivr.logica_principal_ivr(
                    ruta_base = ruta_lectura,
                    metodo = self.metodo,
                    rangos = self.clases,
                    col_ivr = None,
                    val_t15 = self.val_t15,
                    crs_ui = self.val_crs, 
                    umbral_mix = self.val_mix,
                    task = self
                )
                
                dfs_ivr = ivr.informacion_capa_ivr(dfs_ivr, colcl = None,
                          inf_add = self.val_adc, inf_org = self.val_org, 
                          inf_nor = self.val_nor, inf_cls = self.val_gau)
                
                
            # Gestión de información auxiliar    
            
            df_transf, parametros_reg, parametros_estadisticos = ivr.transformacion_sigmoidal_scipy(
                dfs_bi, ivr_loc = True, año_corte = 2026)
            
            # Borrar 
            
            import json 
            ruta_temp  = os.path.join(output_path, "dic_parametros_gau_v1.json")
            with open(ruta_temp, "w", encoding="utf-8") as archivo:
                json.dump(parametros_estadisticos, archivo, ensure_ascii=False, indent=4)
            
            aux.inf_aux_ivr(df_mun, dfs_bi, df_pro, parametros_reg, parametros_estadisticos,
                output = output_path, 
                metodo = self.metodo, rangos = self.clases, 
                fig_sig = self.fsig, fig_nor = self.fnor,
                csv_mun = self.csvmun, csv_prov = self.csvpro)
                                         
            # Información capa 
            QgsMessageLog.logMessage(
                f"Consolidador OK. dfs_ivr tipo={type(dfs_ivr)} filas={len(dfs_ivr)}",
                "IVR", Qgis.Info
            )

            # Ruta gpkg
            if str(output_path).lower().endswith(".gpkg"):
                gpkg_path = output_path
            else:
                os.makedirs(output_path, exist_ok=True)
                gpkg_path = os.path.join(output_path, "ivr.gpkg")
            self.gpkg_path = gpkg_path

            # Convertir GeoDataFrame a capa memoria y guardar con QGIS
            geom_col = None
            try:
                geom_col = qgs.detect_geom_col(dfs_ivr)
            except Exception:
                geom_col = None

            vmem = qgs.gdf_memoria_capa(dfs_ivr, layer_name=self.layer_name, geom_col=geom_col)
            self.setProgress(97)

            qgs.guardar_capa_gpkg(vmem, self.gpkg_path, layer_name=self.layer_name, overwrite_file=True)
            QgsMessageLog.logMessage(f"GeoPackage guardado: {self.gpkg_path}", "IVR", Qgis.Info)

            self.setProgress(99)
            self._result_ok = True
            return True

        except Exception as e:
            self.exception = e
            QgsMessageLog.logMessage(f"ERROR en run(): {repr(e)}", "IVR", Qgis.Critical)
            return False

    def finished(self, result):
        if not result or not self._result_ok:
            QgsMessageLog.logMessage(
                f"Task finished() con fallo. Exception: {repr(self.exception)}",
                "IVR", Qgis.Critical
            )
            return

        QgsMessageLog.logMessage("Task finished() OK. Cargando capa en QGIS…", "IVR", Qgis.Info)

        uri = f"{self.gpkg_path}|layername={self.layer_name}"
        vlayer = QgsVectorLayer(uri, self.layer_name, "ogr")

        if not vlayer.isValid():
            QgsMessageLog.logMessage(
                f"No se pudo cargar la capa (vlayer inválida). URI: {uri}",
                "IVR", Qgis.Critical
            )
            return
        
        if self.metodo != "Sin clasificar":
            qgs.aplicar_simbologia_diccionario(
                vlayer, 
                self.col_ivr, 
                self.dic_gau, 
                opacity = 0.85)


        QgsProject.instance().addMapLayer(vlayer)
        QgsMessageLog.logMessage(
            f"Capa añadida: {self.layer_name} | {self.gpkg_path}",
            "IVR", Qgis.Success
        )
